#!/bin/bash

# add colors to grep and ls
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

# more ls aliases
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'

# git aliases
alias add="git add -u"
alias commit="git commit"
alias gtree="git ls-tree --full-tree -r HEAD"

alias path="echo \$PATH | tr ':' '\n'"

# tmux aliases
function tux { tmux new-session -A -s ${1:-main}; }

