#!/bin/bash

export PYENV_ROOT=$HOME/.pyenv
export WORKON_HOME=$PYENV_ROOT/versions

function setup_pyenv {
    export PATH="/home/ps2958/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
}

# python/conda aliases
# Simple workon function for BASH shells. Tested on Ubuntu 18.04
# Assumes WORKON_HOME is set
function workon {
    WORKON_HOME=${WORKON_HOME:-$HOME/.pyenv/versions}
    [ ! -d "$WORKON_HOME/" ] && echo "WORKON_HOME ($WORKON_HOME) does not exist." 1>&2 && return 1;

    typeset env_name="$1";
    if [ "$env_name" = "" ]; then
        ( builtin \cd "$WORKON_HOME" && echo */bin/activate ) 2> /dev/null | command \tr "\n" " " | 
        command \sed "s|/bin/activate |/|g" | command \tr "/" "\n" | command \sed "/^\s*$/d" | ( unset GREP_OPTIONS; command \egrep -v '^\*$' ) 2> /dev/null
        return 1;
    fi;

    activate="$WORKON_HOME/$env_name/bin/activate";
    if [ ! -f "$activate" ]; then
        echo "Environment '$WORKON_HOME/$env_name' does not contain an activate script." 1>&2;
        return 1;
    fi;
    
    # Activate script
    source "$activate";
}