#!/bin/bash
# ssh helper function 
# Usage: shh username servername
# Add servers with servie[server_alias]='server_address'
declare -A servie

function shh {
  if [[ $# -ne 2 ]]; then
      echo "Usage: ssh username server"
  else
    if [ -z ${servie[$2]} ]; then
        ssh "$1@$2"
    else
        ssh "$1@${servie[$2]}"
    fi
  fi
}

